### ISSUE TITLE
Block based

### ISSUE THREAD

**Issue by suntong** [cathalgarvey/sqrape#4]
Oh, well, I have a feeling that I'm pushing my luck and asking for too much now. However, I do like [andrew's goscrape's architect](https://github.com/andrew-d/goscrape) better: 

- Each scrape consists of some number of *pages*. (already requested/covered in #2)
- Inside each page, there's 1 or more *blocks* - some logical method of splitting
  up a page into subcomponents.  By default, there's a single block that consists
	of the pages's `<body>` element, but you can change this fairly easily.
- Inside each block, you define some number of *pieces* of data that you wish
  to extract.  Each piece consists of a name, a selector, and what data to
	extract from the current block.

The point is that so far everything I want to scrap is block based, it can be a single block as `<body>`, but most of the time there are more blocks. The advantage of this architect is that, within the block, each  *pieces* to be extracted is specified in *relative* form. So, 

- we don't need to repeat ourselves for the block part, 
- when the block is somehow moved, there is one single place to change in the code, instead of all over each pieces

Please consider. Thx.

**Comment by cathalgarvey** [comment]
Hi @suntong - sorry for the delay in responding. :)

Block-based scraping is well-supported using `sqrape` already, you just have to define a top-level struct for the *Page* which contains a slice of whatever *Block* you want to find, and an extractor for finding the blocks. The *Blocks* are their own struct, with their own extractors; those extractors will work relative to the block, not the page. So, `sqrape` operates recursively when you build it like this.

If you look at the Twitter example, it follows this pattern; there is a `Page->Tweet->Field` flow that works well, and extracts all tweets from a page using tweet-relative selectors.

**Comment by suntong** [comment]
Oh I see what you meant. You are talking at the programming level, while I was talking at the declaration level. Anyway, not a big deal. 

BTW, what does "_sqrape_" mean?
